import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { store } from "@/redux/store";
import { Providers } from "../redux/provider";

const montserrat = Montserrat({
  weight: ["300", "400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${montserrat.className} scroll-smooth}`}>
      <body>
        {/* <Providers> */}
          <Navbar />
          {children}
          <Footer />
        {/* </Providers> */}
      </body>
    </html>
  );
}
